# Generated by Django 4.0.2 on 2023-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('professors', '0002_rename_professors_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.ManyToManyField(blank=True, to='home.Faculty'),
        ),
    ]
