# Generated by Django 4.0.2 on 2023-01-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_alter_professor_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='faculty',
            new_name='faculties',
        ),
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='images/professors/default.jpeg', upload_to='images/professors'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
