# Generated by Django 4.0.2 on 2023-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('professors', '0004_rename_faculty_professor_faculties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='faculties',
            field=models.ManyToManyField(to='home.Faculty'),
        ),
    ]
