# Generated by Django 4.0.2 on 2023-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_alter_professor_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/professors'),
        ),
    ]
