# Generated by Django 4.0.2 on 2023-01-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_alter_professor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='image',
            field=models.ImageField(default='images/professors/default.jpg', upload_to='images/professors'),
        ),
    ]
