services:
  postgres-container:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 9998:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  my-site-container:
    build: .
    ports:
      - 9999:8000
    depends_on:
      postgres-container:
        condition: service_healthy