# Generated by Django 4.0.2 on 2023-01-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalCode', models.IntegerField()),
                ('muniplicity', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.address')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(db_index=True, max_length=20, unique=True)),
                ('umcn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('idCardNumber', models.CharField(db_index=True, max_length=14, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('umcn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('idCardNumber', models.CharField(db_index=True, max_length=14, unique=True)),
                ('index', models.CharField(db_index=True, max_length=20, unique=True)),
                ('birthDate', models.DateField()),
                ('image', models.ImageField(upload_to='images/students')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.address')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.faculty')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.parent')),
            ],
        ),
    ]
