# Generated by Django 4.0.2 on 2023-01-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_muniplicity_address_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phoneNumber',
            field=models.CharField(db_index=True, default='021450810', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
